#内置的tomcat服务启动监听端口号
server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shuang11
    username: root
    password: 1973524
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: UserProvider01
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka,http://localhost:8190/eureka
mybatis:
  type-aliases-package: com.offcn.mapper