spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DongShi94/Dd
          search-paths: offcn/config-repo
          username: DongShi94
          password: a1973524
server:
  port: 2000